typedef unsigned char boolean;
typedef signed char sint8;
typedef unsigned char uint8;
typedef short sint16;
typedef unsigned short uint16;
typedef int sint32;
typedef unsigned int uint32;
typedef long long sint64;
typedef unsigned long long uint64;
typedef float float32;
typedef double float64;
typedef unsigned short uint16_t;
typedef unsigned int uint32_t;
typedef float float32_t;
typedef unsigned char bool;
typedef uint8 Std_ReturnType;
void EPWM_clearEventTriggerInterruptFlag();
void set_p_EPWM_clearEventTriggerInterruptFlag(void *f);
uint32_t CPUTimer_getTimerCount();
void set_p_CPUTimer_getTimerCount(void *f);
void Interrupt_clearACKGroup();
void set_p_Interrupt_clearACKGroup(void *f);
